#!/bin/bash
set -euo pipefail
. "${DIR:-$(pwd)}/ghapt-common"

sourceRepos=("Zagrios/bs-manager")

# shellcheck disable=SC2120
h () {
    # if arguments, print them
    [ $# == 0 ] || echo "$*"

  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTION]...
  update the deb list with debs this repo is publishing and push a commit
Available options:
  -h, --help       display this help and exit
  -n, --check      don't modify or push anything, just check if an update is required, exit code 2 if updated needed
EOF

    # if args, exit 1 else exit 0
    [ $# == 0 ] || exit 1
    exit 0
}

# getopt short options go together, long options have commas
TEMP=$(getopt -o hc --long help,check -n "$0" -- "$@")
#shellcheck disable=SC2181
if [ $? != 0 ] ; then
    die "something wrong with getopt"
fi
eval set -- "$TEMP"

check=false
while true ; do
    case "$1" in
        -h|--help) h ;;
        -c|--check) check=true; shift ;;
        --) shift ; break ;;
        *) die "issue parsing args, unexpected argument '$0'!" ;;
    esac
done

# list of updsream debs to deal with, newline separated
listDebs () {
    repo=${1:?Must Provide Repo to generateFileList}
    releaseCount=${2:-1}
    gh release list -R "$repo" --exclude-drafts --exclude-pre-releases --limit "$releaseCount" --json tagName --jq '.[] | .tagName' | xargs -I{} gh release view '{}' -R "$repo" --json assets --jq '.assets[] | .url' | grep ".deb$"
}


newFiles=$(mktemp -t tmp.debGitRepoThing.XXXXXXXXXX,)
trap 'rm -f -- "$newFiles"' EXIT

for repo in "${sourceRepos[@]}"; do
    listDebs "$repo" 1 >> "$newFiles"
done

sort -o "$newFiles" "$newFiles"

if cmp -s "$debList" "$newFiles" ; then
    exit 0
fi

if [ "$check" = true ]; then
    exit 2
fi

echo "deb list updated:"
diff --new-file "$debList" "$newFiles" || true

mv "$newFiles" "$debList"
