#!/bin/bash
set -euo pipefail
. "${DIR:-$(pwd)}/ghapt-common"

# shellcheck disable=SC2120
h () {
    # if arguments, print them
    [ $# == 0 ] || echo "$*"

  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [OPTION]...
  create the repo files Releases and Package
Available options:
  -h, --help                    display this help and exit
EOF

    # if args, exit 1 else exit 0
    [ $# == 0 ] || exit 1
    exit 0
}

# getopt short options go together, long options have commas
TEMP=$(getopt -o h --long help -n "$0" -- "$@")
#shellcheck disable=SC2181
if [ $? != 0 ] ; then
    die "something wrong with getopt"
fi
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h|--help) h ;;
        --) shift ; break ;;
        *) die "issue parsing args, unexpected argument '$0'!" ;;
    esac
done


#TODO cleanup stuff, either always blank or delete signed stuff I dunno
#rm -rf "$repoDir"
#mkdir "$repoDir"
cd "$repoDir"
bash "$DIR/ghapt-scan"
bash "$DIR/ghapt-download"

dpkg-scanpackages --multiversion . > Packages
gzip -k -f Packages

apt-ftparchive release . > Release
